/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author Aliyah Picante
 */
public class AboutMe extends javax.swing.JFrame {

    /**
     * Creates new form AboutMe
     */
    public AboutMe() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        forAboutMe = new javax.swing.JPanel();
        forBtns = new javax.swing.JPanel();
        Home = new javax.swing.JButton();
        myWorks = new javax.swing.JButton();
        contacts = new javax.swing.JButton();
        frdescrip = new javax.swing.JLabel();
        AMScroll = new javax.swing.JScrollPane();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        forAboutMe.setPreferredSize(new java.awt.Dimension(1200, 700));
        forAboutMe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        forBtns.setOpaque(false);

        Home.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setText("Home");
        Home.setContentAreaFilled(false);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        myWorks.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        myWorks.setForeground(new java.awt.Color(255, 255, 255));
        myWorks.setText("My Works");
        myWorks.setContentAreaFilled(false);
        myWorks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myWorksActionPerformed(evt);
            }
        });

        contacts.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        contacts.setForeground(new java.awt.Color(255, 255, 255));
        contacts.setText("Contacts");
        contacts.setContentAreaFilled(false);
        contacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout forBtnsLayout = new javax.swing.GroupLayout(forBtns);
        forBtns.setLayout(forBtnsLayout);
        forBtnsLayout.setHorizontalGroup(
            forBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forBtnsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myWorks, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contacts)
                .addContainerGap())
        );
        forBtnsLayout.setVerticalGroup(
            forBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forBtnsLayout.createSequentialGroup()
                .addGroup(forBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contacts, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myWorks, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        forAboutMe.add(forBtns, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 320, 50));
        forAboutMe.add(frdescrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 480, 410));

        AMScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        AMScroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        AMScroll.setPreferredSize(new java.awt.Dimension(1205, 710));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/BGam.png"))); // NOI18N
        BG.setText("jLabel2");
        AMScroll.setViewportView(BG);

        forAboutMe.add(AMScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(forAboutMe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(forAboutMe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Methods for the buttons
    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        dispose();
        Homepage Homepage = new Homepage();
        Homepage.setVisible(true);
    }//GEN-LAST:event_HomeActionPerformed

    private void myWorksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myWorksActionPerformed
        dispose();
        myWork work = new myWork();
        work.setVisible(true);
    }//GEN-LAST:event_myWorksActionPerformed

    private void contactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactsActionPerformed
        dispose();
        contacts contacts = new contacts();
        contacts.setVisible(true);
    }//GEN-LAST:event_contactsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutMe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane AMScroll;
    private javax.swing.JLabel BG;
    private javax.swing.JButton Home;
    private javax.swing.JButton contacts;
    private javax.swing.JPanel forAboutMe;
    private javax.swing.JPanel forBtns;
    private javax.swing.JLabel frdescrip;
    private javax.swing.JButton myWorks;
    // End of variables declaration//GEN-END:variables
}
