/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author Aliyah Picante
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        forGreetandDescrip = new javax.swing.JPanel();
        forBtns = new javax.swing.JPanel();
        aboutMe = new javax.swing.JButton();
        myWorks = new javax.swing.JButton();
        contacts = new javax.swing.JButton();
        bG = new javax.swing.JLabel();
        gt1 = new javax.swing.JLabel();
        gt2 = new javax.swing.JLabel();
        gt3 = new javax.swing.JLabel();
        gt4 = new javax.swing.JLabel();
        dc1 = new javax.swing.JLabel();
        dc2 = new javax.swing.JLabel();
        dc3 = new javax.swing.JLabel();
        dc4 = new javax.swing.JLabel();
        dc5 = new javax.swing.JLabel();
        dc6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        forGreetandDescrip.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        forBtns.setOpaque(false);

        aboutMe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        aboutMe.setForeground(new java.awt.Color(255, 255, 255));
        aboutMe.setText("About Me");
        aboutMe.setContentAreaFilled(false);
        aboutMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMeActionPerformed(evt);
            }
        });

        myWorks.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        myWorks.setForeground(new java.awt.Color(255, 255, 255));
        myWorks.setText("My Works");
        myWorks.setContentAreaFilled(false);
        myWorks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myWorksActionPerformed(evt);
            }
        });

        contacts.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        contacts.setForeground(new java.awt.Color(255, 255, 255));
        contacts.setText("Contacts");
        contacts.setContentAreaFilled(false);
        contacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout forBtnsLayout = new javax.swing.GroupLayout(forBtns);
        forBtns.setLayout(forBtnsLayout);
        forBtnsLayout.setHorizontalGroup(
            forBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forBtnsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aboutMe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myWorks, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contacts)
                .addContainerGap())
        );
        forBtnsLayout.setVerticalGroup(
            forBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forBtnsLayout.createSequentialGroup()
                .addGroup(forBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contacts, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aboutMe, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myWorks, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        forGreetandDescrip.add(forBtns, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 320, 50));

        bG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/Dashboard.png"))); // NOI18N
        forGreetandDescrip.add(bG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        gt1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        gt1.setForeground(new java.awt.Color(255, 255, 255));
        gt1.setText("Hi,");
        forGreetandDescrip.add(gt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 480, -1));

        gt2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        gt2.setForeground(new java.awt.Color(255, 255, 255));
        gt2.setText("I'm Aliyah");
        forGreetandDescrip.add(gt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 480, 60));

        gt3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        gt3.setForeground(new java.awt.Color(255, 255, 255));
        gt3.setText("France Picante");
        forGreetandDescrip.add(gt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 480, 70));

        gt4.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        gt4.setForeground(new java.awt.Color(255, 255, 255));
        gt4.setText("currently an I.T Student at NU Manila");
        forGreetandDescrip.add(gt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 460, -1));

        dc1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dc1.setForeground(new java.awt.Color(255, 255, 255));
        dc1.setText("I  have  experience  in  PHP,  HTML,  and  CSS.  I'm  into");
        forGreetandDescrip.add(dc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 460, -1));

        dc2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dc2.setForeground(new java.awt.Color(255, 255, 255));
        dc2.setText("designing  websites  using  HTML, and CSS, and I love the");
        forGreetandDescrip.add(dc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 470, -1));

        dc3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dc3.setForeground(new java.awt.Color(255, 255, 255));
        dc3.setText("feeling  of  finishing  a  website  after  hours  and  days  of");
        forGreetandDescrip.add(dc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 470, -1));

        dc4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dc4.setForeground(new java.awt.Color(255, 255, 255));
        dc4.setText("putting effort into it.  This is what led me to website design");
        forGreetandDescrip.add(dc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 480, -1));

        dc5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dc5.setForeground(new java.awt.Color(255, 255, 255));
        dc5.setText("as my passion.  I would love to have any opportunities for");
        forGreetandDescrip.add(dc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, 470, -1));

        dc6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dc6.setForeground(new java.awt.Color(255, 255, 255));
        dc6.setText("my passion and skills to grow");
        forGreetandDescrip.add(dc6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 480, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(forGreetandDescrip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(forGreetandDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Methods for the buttons
    private void aboutMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMeActionPerformed
        dispose();
        AboutMe AboutMe = new AboutMe();
        AboutMe.setVisible(true);
    }//GEN-LAST:event_aboutMeActionPerformed

    private void myWorksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myWorksActionPerformed
        dispose();
        myWork work = new myWork();
        work.setVisible(true);
    }//GEN-LAST:event_myWorksActionPerformed

    private void contactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactsActionPerformed
        dispose();
        contacts contacts = new contacts();
        contacts.setVisible(true);
    }//GEN-LAST:event_contactsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutMe;
    private javax.swing.JLabel bG;
    private javax.swing.JButton contacts;
    private javax.swing.JLabel dc1;
    private javax.swing.JLabel dc2;
    private javax.swing.JLabel dc3;
    private javax.swing.JLabel dc4;
    private javax.swing.JLabel dc5;
    private javax.swing.JLabel dc6;
    private javax.swing.JPanel forBtns;
    private javax.swing.JPanel forGreetandDescrip;
    private javax.swing.JLabel gt1;
    private javax.swing.JLabel gt2;
    private javax.swing.JLabel gt3;
    private javax.swing.JLabel gt4;
    private javax.swing.JButton myWorks;
    // End of variables declaration//GEN-END:variables
}
